### PR TITLE
feat : added loader for waiting state

### PR DESCRIPTION
**Pull request by Sahilm416**
=> feat #4 
=> loader is shown when app is in waiting state.

### CODE REVIEW

**Comment by Sahilm416** [comment]
@praveen8git is there any changes i should do in this PR ??

**Comment by praveen8git** [comment]
Hi Sahil, 
In order to keep the UI minimal, how about adding a loader only where we're displaying the shortened URL, instead of a full page loader? while loading we must disable the submit button too.
What are your thoughts?

**Comment by Sahilm416** [comment]
@praveen8git  sure ! thanks for the review...

**Comment by Sahilm416** [comment]
@praveen8git take a look at these changes.  I have added the the loader only for link section and the shrink button is also disabled while in waiting state.

**Review by praveen8git — APPROVED** [review]
Looks good, I'm merging this PR. thanks

**Pull request merged**
